#!/bin/bash
set -eo pipefail

function wait_till_exists {
  while ! test -f "$1"; do
    sleep 0.1
  done
}

distdir="dist.prof"

if ! test -d "$distdir"
  then
    mkdir "$distdir"
    cabal install --enable-library-profiling --only-dependencies --enable-tests --enable-benchmarks --builddir="$distdir"
    cabal configure --enable-library-profiling --enable-profiling --enable-tests --enable-benchmarks --builddir="$distdir"
  fi;

cabal build profiling -v0 --builddir="$distdir"
cd "$distdir"
rm -f profiling.ps
rm -f profiling.hp
build/profiling/profiling +RTS -N4 -hc -i0.01 -L70 -RTS
hp2ps -e8in -c profiling.hp
wait_till_exists "profiling.ps"
open profiling.ps
