#!/bin/bash
set -eo pipefail

distdir="dist.prof"

if ! test -d "$distdir"
  then
    mkdir "$distdir"
    cabal install --enable-library-profiling --only-dependencies --enable-tests --enable-benchmarks --builddir="$distdir"
    cabal configure --enable-library-profiling --enable-profiling --enable-tests --enable-benchmarks --builddir="$distdir"
  fi;

cabal build profiling -v0 --builddir="$distdir"
cd "$distdir"
build/profiling/profiling +RTS -N4 -p -V0.00001 -RTS
open profiling.prof
