#!/bin/bash
set -eo pipefail

distdir="dist.events"

if ! test -d "$distdir"
  then
    mkdir "$distdir"
    cabal install --only-dependencies --enable-tests --enable-benchmarks --builddir="$distdir"
    cabal configure --disable-library-profiling --enable-tests --enable-benchmarks --builddir="$distdir"
  fi;

cabal build profiling --ghc-options="-eventlog" -v0 --builddir="$distdir"
cd "$distdir"
build/profiling/profiling +RTS -N4 -la -RTS
ghc-events-analyze --timed --bucket-width 1 --bucket-height 14 --border-width 0 --ms --tick-every 20 --buckets 1000 --window Session profiling.eventlog
open profiling.0.timed.svg
threadscope profiling.eventlog
