#!/bin/bash
set -eo pipefail

cabal build profiling --ghc-options="-O2 -j -threaded -eventlog"
cd dist
build/profiling/profiling +RTS -N4 -ls -lf -RTS
ghc-events-analyze profiling.eventlog
threadscope profiling.eventlog
