#!/bin/bash
set -eo pipefail

function wait_till_exists {
  while ! test -f "$1"; do
    sleep 0.1
  done
}

cabal build profiling
cd dist
rm -f profiling.ps
rm -f profiling.hp
build/profiling/profiling +RTS -N4 -s -hc -i0.01 -L70 -RTS
hp2ps -e8in -c profiling.hp
wait_till_exists "profiling.ps"
open profiling.ps
