name: Compile and test

on:
  workflow_call:
    inputs:
      qc-max-success:
        description: Maximum number of successful tests for QuickCheck
        required: false
        type: number
        default: 10000

jobs:

  check-cabal:
    uses: nikita-volkov/haskell-hackage-lib-github-actions-workflows/.github/workflows/check-cabal.yaml@v4
    secrets: inherit

  build-with-ghc-8-10:
    uses: nikita-volkov/haskell-hackage-lib-github-actions-workflows/.github/workflows/build.yaml@v4
    secrets: inherit
    with:
      ghc: "8.10"
      skip-benchmarks: true
      test-options: --qc-max-success=100

  build-with-latest:
    uses: nikita-volkov/haskell-hackage-lib-github-actions-workflows/.github/workflows/build.yaml@v4
    secrets: inherit
    with:
      test-options: --qc-max-success=${{ inputs.qc-max-success }}
