name: CI

on:
  pull_request:
  push:
    branches: [main, master]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  ci:
    uses: nikita-volkov/haskell-hackage-lib-github-actions-workflows/.github/workflows/ci.yaml@v5
    secrets: inherit
    with:
      test-options: --qc-max-success=10000
