on:
  pull_request:

concurrency:
  group: pr-validation-${{ github.ref }}
  cancel-in-progress: true

jobs:

  generate-docs:
    uses: nikita-volkov/haskell-hackage-lib-github-actions-workflows/.github/workflows/generate-docs.yaml@v4
    secrets: inherit

  check:
    uses: ./.github/workflows/check.yaml
    secrets: inherit
    with:
      qc-max-success: 1000
