on:
  push:
    branches:
      - supermajor
      - major
      - minor
      - patch

concurrency:
  group: release
  cancel-in-progress: false

jobs:

  format:
    uses: ./.github/workflows/format.yaml
    secrets: inherit
  
  check:
    uses: ./.github/workflows/check.yaml
    secrets: inherit
  
  release:
    needs:
      - format
      - check
    uses: nikita-volkov/haskell-hackage-lib-github-actions-workflows/.github/workflows/release.yaml@v4
    secrets: inherit
    with:
      prefix-tag-with-v: false
      docs: true

  deploy-docs-to-pages:
    needs:
      - release
    uses: ./.github/workflows/deploy-docs-to-pages.yaml
    secrets: inherit
