on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  format:
    uses: ./.github/workflows/format.yaml
    secrets: inherit

  check:
    uses: ./.github/workflows/check.yaml
    secrets: inherit

  deploy-docs-to-pages:
    uses: ./.github/workflows/deploy-docs-to-pages.yaml
    secrets: inherit
